package vault

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestGenerateSlug(t *testing.T) {
	tests := []struct {
		name     string
		prompt   string
		expected string
	}{
		{
			name:     "basic",
			prompt:   "something my picky kid would love",
			expected: "something-my-picky-kid-would",
		},
		{
			name:     "more than 5 words",
			prompt:   "something my picky kid would love to eat",
			expected: "something-my-picky-kid-would",
		},
		{
			name:     "with special chars",
			prompt:   "quick! easy & tasty recipes?",
			expected: "quick-easy-tasty-recipes",
		},
		{
			name:     "uppercase",
			prompt:   "Hello World Test Case",
			expected: "hello-world-test-case",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := generateSlug(tt.prompt)
			if got != tt.expected {
				t.Errorf("generateSlug(%q) = %q, want %q", tt.prompt, got, tt.expected)
			}
		})
	}
}

func TestStripHTML(t *testing.T) {
	tests := []struct {
		name     string
		html     string
		expected string
	}{
		{
			name:     "no tags",
			html:     "plain text",
			expected: "plain text",
		},
		{
			name:     "single tag",
			html:     "<p>Hello</p>",
			expected: "Hello",
		},
		{
			name:     "multiple tags",
			html:     "<p>Hello <b>world</b></p>",
			expected: "Hello world",
		},
		{
			name:     "with attributes",
			html:     `<img src="test.jpg" alt="test">`,
			expected: "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := stripHTML(tt.html)
			if got != tt.expected {
				t.Errorf("stripHTML(%q) = %q, want %q", tt.html, got, tt.expected)
			}
		})
	}
}

func TestTruncateSummary(t *testing.T) {
	tests := []struct {
		name     string
		summary  string
		maxLen   int
		expected string
	}{
		{
			name:     "within limit",
			summary:  "Short text",
			maxLen:   100,
			expected: "Short text",
		},
		{
			name:     "exact limit",
			summary:  "Exactly ten",
			maxLen:   11,
			expected: "Exactly ten",
		},
		{
			name:     "needs truncation",
			summary:  "This is a longer text that needs to be truncated",
			maxLen:   10,
			expected: "This is a...",
		},
		{
			name:     "truncate at word boundary",
			summary:  "This is a test summary that should be truncated properly at word boundaries",
			maxLen:   20,
			expected: "This is a test...",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := truncateSummary(tt.summary, tt.maxLen)
			if got != tt.expected {
				t.Errorf("truncateSummary(%q, %d) = %q, want %q", tt.summary, tt.maxLen, got, tt.expected)
			}
		})
	}
}

func TestWriteSession(t *testing.T) {
	// Create a temporary directory
	tmpDir := t.TempDir()

	// Create a test session
	session := Session{
		Prompt:      "something my picky kid would love",
		SearchTerms: []string{"chicken", "pasta", "easy"},
		Recipes: []Recipe{
			{
				ID:             1,
				Title:          "Chicken Pasta",
				Image:          "https://example.com/chicken.jpg",
				ReadyInMinutes: 30,
				Servings:       4,
				SourceURL:      "https://example.com/recipe/1",
				Summary:        "A <b>delicious</b> chicken pasta dish",
				Cuisines:       []string{"Italian", "Mediterranean"},
				Diets:          []string{"Gluten-Free", "Paleo"},
			},
		},
		VaultPath: tmpDir,
	}

	// Write session
	filePath, err := WriteSession(session)
	if err != nil {
		t.Fatalf("WriteSession() returned error: %v", err)
	}

	// Verify file exists
	if _, err := os.Stat(filePath); err != nil {
		t.Fatalf("File not created at %s: %v", filePath, err)
	}

	// Verify directory structure
	expectedDir := filepath.Join(tmpDir, "Recipes")
	if _, err := os.Stat(expectedDir); err != nil {
		t.Fatalf("Recipes directory not created at %s: %v", expectedDir, err)
	}

	// Verify file contains expected content
	content, err := os.ReadFile(filePath)
	if err != nil {
		t.Fatalf("Failed to read file: %v", err)
	}

	contentStr := string(content)

	// Check for key elements in the markdown
	checks := []struct {
		name     string
		mustHave string
	}{
		{"Title", "# Recipes: something my picky kid would love"},
		{"Date", time.Now().Format("2006-01-02")},
		{"Recipe count", "**Recipes saved:** 1"},
		{"Search terms", "chicken · pasta · easy"},
		{"Recipe title", "## Chicken Pasta"},
		{"HTML stripping", "A delicious chicken pasta dish"},
		{"Ready time", "30 min"},
		{"Servings", "4"},
		{"Cuisines", "Italian, Mediterranean"},
		{"Diets", "Gluten-Free, Paleo"},
		{"Source link", "[Recipe Link](https://example.com/recipe/1)"},
		{"Generated by footer", "*Generated by recipeme on"},
	}

	for _, check := range checks {
		if !strings.Contains(contentStr, check.mustHave) {
			t.Errorf("Content missing expected element (%s): %q", check.name, check.mustHave)
		}
	}

	// Verify file name format
	expectedFileName := "Recipes - something-my-picky-kid-would - " + time.Now().Format("2006-01-02") + ".md"
	actualFileName := filepath.Base(filePath)
	if actualFileName != expectedFileName {
		t.Errorf("File name = %q, want %q", actualFileName, expectedFileName)
	}
}
