package vault

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"
	"time"
	"unicode"
)

// htmlTagRe is compiled once at package level for efficient reuse
var htmlTagRe = regexp.MustCompile("<[^>]+>")

// Recipe represents a recipe with all relevant details.
type Recipe struct {
	ID               int
	Title            string
	Image            string
	ReadyInMinutes   int
	Servings         int
	SourceURL        string
	Summary          string
	Cuisines         []string
	Diets            []string
	SpoonacularScore float64
}

// Session represents a recipe search session.
type Session struct {
	Prompt      string
	SearchTerms []string
	Recipes     []Recipe
	VaultPath   string
}

// generateSlug creates a slug from the first 5 words of the prompt.
// Spaces are replaced with hyphens, non-alphanumeric characters (except hyphens) are stripped,
// and consecutive hyphens are collapsed to a single hyphen.
func generateSlug(prompt string) string {
	words := strings.Fields(prompt)
	if len(words) > 5 {
		words = words[:5]
	}

	slug := strings.Join(words, "-")

	// Remove non-alphanumeric characters except hyphens
	var result strings.Builder
	for _, r := range slug {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '-' {
			result.WriteRune(unicode.ToLower(r))
		}
	}

	// Collapse consecutive hyphens to a single hyphen
	slug = result.String()
	for strings.Contains(slug, "--") {
		slug = strings.ReplaceAll(slug, "--", "-")
	}

	return slug
}

// stripHTML removes HTML tags from a string.
func stripHTML(html string) string {
	return htmlTagRe.ReplaceAllString(html, "")
}

// truncateSummary truncates summary to ~300 chars at a word boundary and appends "..." if truncated.
func truncateSummary(summary string, maxLen int) string {
	if len(summary) <= maxLen {
		return summary
	}

	// Truncate to maxLen
	truncated := summary[:maxLen]

	// Find the last space to truncate at word boundary
	lastSpace := strings.LastIndex(truncated, " ")
	if lastSpace > 0 {
		truncated = truncated[:lastSpace]
	}

	return truncated + "..."
}

// Writer wraps the vault path and implements the VaultWriter interface expected by handlers.
type Writer struct {
	vaultPath string
}

// NewWriter creates a new Writer for the given vault path.
func NewWriter(vaultPath string) *Writer {
	return &Writer{vaultPath: vaultPath}
}

// WriteSession implements handlers.VaultWriter by injecting the vault path into the session.
func (w *Writer) WriteSession(s Session) (string, error) {
	s.VaultPath = w.vaultPath
	return writeSession(s)
}

// writeSession writes a session's recipes to an Obsidian-compatible markdown file.
// File path format: {VaultPath}/Recipes/Recipes - {slug} - {date}.md
// Returns the absolute file path written.
func writeSession(s Session) (string, error) {
	// Create Recipes directory
	recipesDir := filepath.Join(s.VaultPath, "Recipes")
	if err := os.MkdirAll(recipesDir, 0o755); err != nil {
		return "", fmt.Errorf("failed to create recipes directory: %w", err)
	}

	// Generate slug and date
	slug := generateSlug(s.Prompt)
	date := time.Now().Format("2006-01-02")

	// Generate file name and path
	fileName := fmt.Sprintf("Recipes - %s - %s.md", slug, date)
	filePath := filepath.Join(recipesDir, fileName)

	// Prepare template data
	templateData := map[string]interface{}{
		"Prompt":      s.Prompt,
		"Date":        date,
		"Count":       len(s.Recipes),
		"SearchTerms": s.SearchTerms,
		"Recipes":     s.Recipes,
	}

	// Create and execute template
	tmpl, err := template.New("session").Funcs(template.FuncMap{
		"stripHTML": stripHTML,
		"truncate":  truncateSummary,
		"join":      strings.Join,
	}).Parse(sessionTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	// Write to file
	file, err := os.Create(filePath)
	if err != nil {
		return "", fmt.Errorf("failed to create file: %w", err)
	}
	defer file.Close()

	if err := tmpl.Execute(file, templateData); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	// Return absolute path
	absPath, err := filepath.Abs(filePath)
	if err != nil {
		return "", fmt.Errorf("failed to get absolute path: %w", err)
	}

	return absPath, nil
}

const sessionTemplate = `# Recipes: {{.Prompt}}

**Session date:** {{.Date}}
**Recipes saved:** {{.Count}}
**Searched for:** {{range $i, $term := .SearchTerms}}{{if $i}} · {{end}}{{$term}}{{end}}

---
{{range .Recipes}}

## {{.Title}}

![{{.Title}}]({{.Image}})

- **Ready in:** {{.ReadyInMinutes}} min · **Servings:** {{.Servings}}
- **Cuisines:** {{join .Cuisines ", "}} · **Diets:** {{join .Diets ", "}}
- **Source:** [Recipe Link]({{.SourceURL}})

> {{truncate (stripHTML .Summary) 300}}

---
{{end}}

*Generated by recipeme on {{.Date}}*
`
